<?php
return array (
  'chenghu' => 
  array (
    'fieldid' => '129',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'chenghu',
    'name' => '称呼',
    'tips' => '请输入姓名',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'phone' => 
  array (
    'fieldid' => '130',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'phone',
    'name' => '联系方式',
    'tips' => '请留下电话或者QQ号码，以便合作律师联系您',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '20',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'liuyandate' => 
  array (
    'fieldid' => '134',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'liuyandate',
    'name' => '留言时间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请填写提交时间',
    'formtype' => 'datetime',
    'setting' => '{"fieldtype":"int","format":"Y-m-d H:i","defaulttype":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '30',
    'disabled' => '0',
    'isomnipotent' => '0',
    'fieldtype' => 'int',
    'format' => 'Y-m-d H:i',
    'defaulttype' => '0',
  ),
  'lycontent2' => 
  array (
    'fieldid' => '133',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'lycontent2',
    'name' => '提问内容',
    'tips' => '请输入提问内容',
    'css' => 'class=mt10',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => '{"width":"100%","height":"246","defaultvalue":"","enablehtml":"1"}',
    'formattribute' => 'cols="90" ',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '40',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '100%',
    'height' => '246',
    'defaultvalue' => '',
    'enablehtml' => '1',
  ),
);
?>